# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datatransfer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x61tatransfer.proto\x12\x02\x64t\"S\n\x12\x44\x61taTransferRecord\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x62ytes\x18\x02 \x01(\x05\x12\x0f\n\x07packets\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x05\"\x18\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\tTimestamp\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\"\x16\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\x02\"\"\n\x14\x44\x61taTransferRecordId\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xe5\x02\n\x0c\x44\x61taTransfer\x12-\n\x06\x43reate\x12\x16.dt.DataTransferRecord\x1a\t.dt.Reply\"\x00\x12:\n\x04Read\x12\x18.dt.DataTransferRecordId\x1a\x16.dt.DataTransferRecord\"\x00\x12-\n\x06Update\x12\x16.dt.DataTransferRecord\x1a\t.dt.Reply\"\x00\x12/\n\x06\x44\x65lete\x12\x18.dt.DataTransferRecordId\x1a\t.dt.Reply\"\x00\x12!\n\x03Min\x12\r.dt.Timestamp\x1a\t.dt.Value\"\x00\x12!\n\x03Max\x12\r.dt.Timestamp\x1a\t.dt.Value\"\x00\x12!\n\x03\x41vg\x12\r.dt.Timestamp\x1a\t.dt.Value\"\x00\x12!\n\x03Sum\x12\r.dt.Timestamp\x1a\t.dt.Value\"\x00\x42\x12\xaa\x02\x0f\x44\x61tabaseServiceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datatransfer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\017DatabaseService'
  _globals['_DATATRANSFERRECORD']._serialized_start=26
  _globals['_DATATRANSFERRECORD']._serialized_end=109
  _globals['_REPLY']._serialized_start=111
  _globals['_REPLY']._serialized_end=135
  _globals['_TIMESTAMP']._serialized_start=137
  _globals['_TIMESTAMP']._serialized_end=167
  _globals['_VALUE']._serialized_start=169
  _globals['_VALUE']._serialized_end=191
  _globals['_DATATRANSFERRECORDID']._serialized_start=193
  _globals['_DATATRANSFERRECORDID']._serialized_end=227
  _globals['_DATATRANSFER']._serialized_start=230
  _globals['_DATATRANSFER']._serialized_end=587
# @@protoc_insertion_point(module_scope)
